#!/usr/bin/python3
# -*- coding: utf-8 -*-
import re
import sys
import ssl

ssl._create_default_https_context = ssl._create_unverified_context

from weasyprint.__main__ import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
